#ifndef __MBTABLE_H__
#define __MBTABLE_H__
#include <stdint.h>
enum out_value {
    OUT_LOW,
    OUT_HIGH,
    OUT_HIGH_PULSE_100MS,
	OUT_HIGH_PULSE_200MS,
    OUT_HIGH_PULSE_500MS,
    OUT_HIGH_PULSE_800MS,
    OUT_HIGH_PULSE_1S,
	OUT_HIGH_PULSE_1500MS,
    OUT_HIGH_PULSE_2S,
    OUT_HIGH_PULSE_4S,
};

enum {
	IN_STATE_IN0=0,
	IN_STATE_IN1,
	IN_STATE_IN2,
	IN_STATE_IN3,
	IN_STATE_IN4,
	IN_STATE_IN5,
	IN_STATE_IN6,
	IN_STATE_IN7,
	IN_STATE_IN8,
	IN_STATE_IN9,
	IN_STATE_IN10,
	IN_STATE_IN11,
	IN_STATE_IN12,
	IN_STATE_IN13,
	IN_STATE_IN14,
	IN_STATE_IN15,
	IN_STATE_OUT3,
	IN_STATE_OUT4,
	IN_STATE_OUT5,
	IN_STATE_OUT6,
	IN_STATE_OUT7,
	IN_STATE_OUT8,
	IN_STATE_OUT9,
	IN_STATE_OUT10,
	IN_STATE_ARM_IO_OUT0,
	IN_STATE_ARM_IO_OUT1,
	IN_STATE_OUT1,
	IN_STATE_OUT2,
    OUT_MODE_OUT3,
	OUT_MODE_OUT4,
	OUT_MODE_OUT5,
	OUT_MODE_OUT6,
	OUT_MODE_OUT7,
	OUT_MODE_OUT8,
	OUT_MODE_OUT9,
	OUT_MODE_OUT10,
	OUT_MODE_ARM_IO_OUT0,
	OUT_MODE_ARM_IO_OUT1,
	OUT_MODE_OUT1,
	OUT_MODE_OUT2,
	IO_STATE_QTY,
};

void mbtable_set(uint16_t raddr,uint16_t value);
int mbtable_get(uint16_t raddr,uint16_t *value);

#endif//__MBTABLE_H__